version: "3.8"

services:
   lite:
      build:
         dockerfile: dockerfile
      image: lite:SNAPSHOT
      ports:
         - "8081:8081"
      restart: on-failure
      depends_on:
         - rabbitmq
      networks:
         vpcbr:
            ipv4_address: 0.0.0.0
      volumes:
         - ./dados:/var/lib/lites/
   rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: always
      ports:
         - "5672:5672"
         - "15672:15672"
      volumes:
         - ./dados:/var/lib/rabbitmq/
      networks:
         vpcbr:
            ipv4_address: 0.0.0.0

networks:
   vpcbr:
      driver: host
      ipam:
         config:
            -  subnet: 0.0.0.0/16
               gateway: 0.0.0.0