version: "3.8"

services:
   lite:
      build:
         dockerfile: dockerfile
      image: lite:SNAPSHOT
      ports:
         - "8081:8081"
      expose:
         - 8081:8081
      restart: on-failure
      depends_on:
         - rabbitmq
      volumes:
         - ./dados:/var/lib/lites/
      cpus: 0.5
      mem_limit: 350m
   rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: always
      ports:
         - "5672:5672"
         - "15672:15672"
      volumes:
         - ./dados:/var/lib/rabbitmq/
      cpus: 0.5
      mem_limit: 150m