logging:
  level:
    com.bats.lite.service: TRACE

server:
  compression:
    enabled: true
  port: 8081
  servlet:
    context-path: /batsworks


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: Lites
  datasource:
    url: jdbc:sqlite:src/main/resources/main.db
    driver-class-name: org.sqlite.JDBC
    hikari:
       maximum-pool-size: 1
  jpa:
    database-platform: com.bats.lite.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASS}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest