logging:
  level:
    com.bats.lite.feign: DEBUG
    com.bats.lite.service: TRACE

server:
  compression:
    enabled: true
  port: 8081
  servlet:
    context-path: /batsworks


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: Lites
  datasource:
    url: jdbc:sqlite:src/main/resources/main.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      minimumIdle: 2
      maximumPoolSize: 20
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  jpa:
    database-platform: com.bats.lite.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASS}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: 192.168.1.226
    port: 5672
    username: guest
    password: guest


request:
  feign:
    tipo: "json/"
    url-cotacao: "https://economia.awesomeapi.com.br/"
    ultimas: "/last/"
    diario: "/daily/"

feign:
  client:
    config:
      default:
        connectTimeout: 40000
        readTimeout: 40000
        loggerLevel: full


api:
  security-secret: ${JWT:GETSHUGA_TENSHOU}